#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include "md5.h"

// generated by chatgpt, may need to debug later..

void md5ToString(uint8_t *digest, char *output) {
    for (int i = 0; i < 16; i++) {
        sprintf(output + (i * 2), "%02x", digest[i]);
    }
    output[32] = '\0';
}

void calculateFileMD5(const char *filePath) {
    FILE *file = fopen(filePath, "rb");
    if (!file) {
        perror("Error opening file");
        return;
    }

    uint8_t digest[16];
    md5File(file, digest);
    fclose(file);

    char hashString[33];
    md5ToString(digest, hashString);

    printf("MD5 (%s) = %s\n", filePath, hashString);
}

void countMatchingMD5Files(const char *directoryPath, const char *targetHash) {
    DIR *dir = opendir(directoryPath);
    if (!dir) {
        perror("Error opening directory");
        return;
    }

    struct dirent *entry;
    int count = 0;

    while ((entry = readdir(dir)) != NULL) {
        if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0) {
            continue;
        }

        char filePath[1024];
        snprintf(filePath, sizeof(filePath), "%s/%s", directoryPath, entry->d_name);

        struct stat pathStat;
        if (stat(filePath, &pathStat) == -1) {
            perror("Error getting file stats");
            continue;
        }

        if (S_ISREG(pathStat.st_mode)) {
            FILE *file = fopen(filePath, "rb");
            if (!file) {
                perror("Error opening file");
                continue;
            }

            uint8_t digest[16];
            md5File(file, digest);
            fclose(file);

            char hashString[33];
            md5ToString(digest, hashString);

            if (strcmp(hashString, targetHash) == 0) {
                count++;
            }
        }
    }

    closedir(dir);

    printf("Files in %s matching MD5 %s: %d\n", directoryPath, targetHash, count);
}

int main(int argc, char *argv[]) {
    if (argc < 3) {
        printf("Usage:\n");
        printf("  %s -f <file_path>\n", argv[0]);
        printf("  %s -d <directory_path> -h <md5_hash>\n", argv[0]);
        return 1;
    }

    if (strcmp(argv[1], "-f") == 0 && argc == 3) {
        calculateFileMD5(argv[2]);
    } else if (strcmp(argv[1], "-d") == 0 && strcmp(argv[3], "-h") == 0 && argc == 5) {
        countMatchingMD5Files(argv[2], argv[4]);
    } else {
        printf("Invalid arguments.\n");
        printf("Usage:\n");
        printf("  %s -f <file_path>\n", argv[0]);
        printf("  %s -d <directory_path> -h <md5_hash>\n", argv[0]);
        return 1;
    }

    return 0;
}
